
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'db/seeds.rb'
    - 'app/jobs/scrape_job.rb'
